package sacco;

import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame{

    Connection con;
    PreparedStatement statement;
    Statement st;
    String cs;
    String user;
    String password;
    String query;
    String records;
    ResultSet rs;
    boolean nxt;
    
    public Login() {
        con = null;
        st = null;
        statement = null;
        cs = "jdbc:mysql://localhost:3306/sacco_db";
        user = "root";
        password = "";
        nxt = false;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logParentPanel = new javax.swing.JPanel();
        loginBtn = new javax.swing.JButton();
        forgotPass = new javax.swing.JLabel();
        logCopyright = new javax.swing.JLabel();
        logTitle1 = new javax.swing.JLabel();
        loginHere1 = new javax.swing.JLabel();
        logUsername1 = new javax.swing.JLabel();
        logPass1 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        userPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login to Kasacco");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(190, 20, 220));

        logParentPanel.setBackground(new java.awt.Color(133, 213, 245));
        logParentPanel.setAutoscrolls(true);
        logParentPanel.setFocusable(false);

        loginBtn.setText("Log In");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        forgotPass.setText("Forgot Password?");
        forgotPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPassMouseClicked(evt);
            }
        });

        logCopyright.setText("2019 © Kasacco Group. All Rights Reserved");

        logTitle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logTitle1.setText("KARUGUTU SAVINGS AND CO-OPERATIVE SOCIETY ");

        loginHere1.setText("Administrator Login");

        logUsername1.setText("Username:");

        logPass1.setText("Password:");

        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout logParentPanelLayout = new javax.swing.GroupLayout(logParentPanel);
        logParentPanel.setLayout(logParentPanelLayout);
        logParentPanelLayout.setHorizontalGroup(
            logParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logParentPanelLayout.createSequentialGroup()
                .addGroup(logParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logParentPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(logTitle1))
                    .addGroup(logParentPanelLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(logParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginHere1))))
                .addGap(0, 88, Short.MAX_VALUE))
            .addGroup(logParentPanelLayout.createSequentialGroup()
                .addGroup(logParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(logParentPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(logParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logUsername1)
                            .addComponent(logPass1))
                        .addGroup(logParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logParentPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(logParentPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(logParentPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(logCopyright))
                    .addGroup(logParentPanelLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(forgotPass)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logParentPanelLayout.setVerticalGroup(
            logParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logParentPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logTitle1)
                .addGap(18, 18, 18)
                .addComponent(loginHere1)
                .addGap(32, 32, 32)
                .addGroup(logParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logUsername1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(logParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logPass1))
                .addGap(40, 40, 40)
                .addComponent(loginBtn)
                .addGap(43, 43, 43)
                .addComponent(forgotPass)
                .addGap(45, 45, 45)
                .addComponent(logCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logParentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String usernam = usernameText.getText();
        String pass = userPassword.getText();
        
        if(usernam.isEmpty() && pass.isEmpty()){
            JOptionPane.showMessageDialog(null, "Fields Can't be left Empty!");
        }
        try{
          Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(cs,user,password);
            st = con.createStatement();
            query = "SELECT * FROM login where userName='"+usernam+"' and password='"+pass+"'";
      
            rs =  st.executeQuery(query);
            
           if(rs.next()){
               String username =rs.getString("userName");
               String password =rs.getString("password");
               if(pass.equals(password) && usernam.equals(username)){
               
               
               dispose();
               MainView mv = new MainView();
               mv.setVisible(true);
               
           }
           }
           else{
               JOptionPane.showMessageDialog(null,"Incorrect Username or Password!");
               usernameText.setText("");
               userPassword.setText("");
               
               usernameText.requestFocus();
           }
           }   
     
         catch(MySQLIntegrityConstraintViolationException esp){
             JOptionPane.showMessageDialog(null, "Current user already exists");
         }
        catch(SQLException ex)
                {
                    ex.printStackTrace();
                }
        catch(ClassNotFoundException e)
        {
            e.printStackTrace();
        }
     
           
        try {
            if(rs!=null){
               rs.close(); 
            }
            
            if(con!=null){
               con.close(); 
            }
            
           
        } catch (SQLException ex) {
           
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void forgotPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotPassMouseClicked

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new Login().setTitle("Login to Kasacco");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forgotPass;
    private javax.swing.JLabel logCopyright;
    private javax.swing.JPanel logParentPanel;
    private javax.swing.JLabel logPass1;
    private javax.swing.JLabel logTitle1;
    private javax.swing.JLabel logUsername1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginHere1;
    private javax.swing.JPasswordField userPassword;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
